openapi: 3.0.3
info:
  version: 1.0.0 
  title: Sample API
  description: A sample API to illustrate OpenAPI concepts
paths:
  /count:
    get:
      description: outputs the number of time each URL was visited
      responses:
        default:
          description: Successful response
          content:
            application/json:
              schema: 
                type: 
                  string
              examples:
                no visits:
                  value: You have not visited anyone yet
  /hello/kitty:
    get:
      description: HTML with a hello kitty image
      responses:
        default:
          description: Successful response
          content:
            application/json:
              schema: 
                type: 
                  string
              examples:
                hello kitty:
                  value: >-
                    <img
                    src="https://upload.wikimedia.org/wikipedia/en/0/05/Hello_kitty_character_portrait.png">
  /hello/{name}:
    get:
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
          description: says hello to the name
      description: says hello to someone
      responses:
        default:
          description: Successful response
          content:
            application/json:
              schema: 
                type: 
                  string
              examples:
                hello-world:
                  value: Hello, world
